### PR TITLE
Fix for new way to change the language base on the actual filename

### PR DESCRIPTION
**Pull request by michael-milette**
Signed-off-by: Michael Milette michael.milette@instruxmedia.com

### CODE REVIEW

**Comment by michael-milette** [comment]
Hi @upsonp 

Your current code assumes that the language is specified by a "-en" or "-fr" in the $_SERVER['REQUEST_URI']

... But what if it isn't? Here is your current code:

```
//new way to change the language base on the actual filename
$q= $_SERVER['REQUEST_URI'];
if (preg_match('/-en\./', $q) > 0) {
    $q = preg_replace('/-en\./', '-fr.', $q);
}
else if (preg_match('/-fr\./', $q) > 0) {
    $q = preg_replace('/-fr\./', '-en.', $q);
}
```

Should the above two preg_match() functions fail, as it stands, language switching doesn't occur at all.

The solution is to add an additional "else". Here is my recommendation:

```
//new way to change the language base on the actual filename
$q= $_SERVER['REQUEST_URI'];
if (preg_match('/-en\./', $q) > 0) {
    $q = preg_replace('/-en\./', '-fr.', $q);
}
else if (preg_match('/-fr\./', $q) > 0) {
    $q = preg_replace('/-fr\./', '-en.', $q);
} else {
    $q = $_SITE['gcwu_cmblang_href_' . $_PAGE['lang'.$i]];
}
```

If WET 4.0 uses the same piece of code, this is going to be an issue for me in both WET 3.1 and 4.x.

Let me know if you have any questions.

Best regards,

Michael Milette

**Comment by upsonp** [comment]
Actually it appears the language switching is broken in v3.1 as well so something needs to be done. How did I not catch that?

**Comment by upsonp** [comment]
@michael-milette Slight modification to your suggestion

The code takes place outside the for-loop so we can't append a $i to the 'lang' in <code>$_PAGE['lang'.$1];</code>. I've come up with a work around for now, but we'll have to revisit in the future I think. 

``` php
//new way to change the language base on the actual filename
$q= $_SERVER['REQUEST_URI'];
if (preg_match('/-en\./', $q) > 0) {
    $q = preg_replace('/-en\./', '-fr.', $q);
} else if (preg_match('/-fr\./', $q) > 0) {
    $q = preg_replace('/-fr\./', '-en.', $q);
} else {
    //if the Request URI doesn't end with a -en or a -fr then blank it and use the
    //$_SITE['gcwu_cmbland_href_' .$_PAGE['lang'.$i]] variable. The user should have
    //either set the variable to point to a static page change or it should be pointing
    //to the script file that's used for language changing.
    $q = '';
}
if( $_PAGE['nolang'] != "1" ) {
        for($i=2; isset($_PAGE['lang'.$i]); $i++ ) {
                if( $q == '' ) {
                    $q = $_SITE['gcwu_cmblang_href_' . $_PAGE['lang'.$i]];
                }
                echo '<li id="gcwu-gcnb-lang';
                if( $i-1 >= 2 ) {
                        echo "-" .($i-1);
                }
                echo '">';
                echo '<a href="' .$q;
                echo '" lang="' .$_SITE['wb_meta_' . $_PAGE['lang'.$i]];
                echo '">' . $_SITE['gcwu_cmblang_text_' . $_PAGE['lang'.$i]]; ;
                echo '</a></li>';
        }
}
```

@crochefort @michael-milette is there a reason we changed to this method instead of just using

``` php
if( $_PAGE['nolang'] != "1" ) {
        for($i=2; isset($_PAGE['lang'.$i]); $i++ ) {
                echo '<li id="gcwu-gcnb-lang';
                if( $i-1 >= 2 ) {
                        echo "-" .($i-1);
                }
                echo '">';
                echo '<a href="' .$_SITE['gcwu_cmblang_href_' . $_PAGE['lang'.$i]];
                echo '" lang="' .$_SITE['wb_meta_' . $_PAGE['lang'.$i]];
                echo '">' . $_SITE['gcwu_cmblang_text_' . $_PAGE['lang'.$i]]; ;
                echo '</a></li>';
        }
}
```

It seems to me the section

``` php
if (preg_match('/-en\./', $q) > 0) {
    $q = preg_replace('/-en\./', '-fr.', $q);
} else if (preg_match('/-fr\./', $q) > 0) {
    $q = preg_replace('/-fr\./', '-en.', $q);
} else {
    //if the Request URI doesn't end with a -en or a -fr then blank it and use the
    //$_SITE['gcwu_cmbland_href_' .$_PAGE['lang'.$i]] variable. The user should have
    //either set the variable to point to a static page change or it should be pointing
    //to the script file that's used for language changing.
    $q = '';
}
```

is doing exactly what the <a href="https://github.com/upsonp/wet-boew-php/blob/master/dist-php/langselect/lang.php">language select script</a> was doing anyway.

Although neither solution is optimal and assumes only English and French are being used.

**Comment by crochefort** [comment]
I think it came from this one : https://github.com/wet-boew/wet-boew-php/commit/f8751aa53eab40838aabb42d1360391d621cc0fa

See this one too : https://github.com/wet-boew/wet-boew-php/commit/c04be5180e0ab6c16e46f8c7f5f1e672a5293934

Was causing some issue with the language selector.

From an english page was just refresh the page, so I test with the filename. 

What we can do is just add a variable in the config that will set witch language we have on our website and it will solve the problem no?

like : site_language : "en","fr","es";

I dont remember but I think it was Transport Canada that they have A website with 3 language and It was switching only between french and english... cannot find the url.

**Comment by michael-milette** [comment]
Hi @upsonp,

Checked out your code, looks good and works. I missed that one about the $i outside the loop. My bad. I just blindly copied the line that had previously been commented out. Thanks for catching it.

Here is a slight optimization of your suggestion. I moved the whole $q definition inside the first IF since it isn't used anywhere else:

``` php
if( $_PAGE['nolang'] != "1" ) {
    //new way to change the language base on the actual filename
    $q= $_SERVER['REQUEST_URI'];
    if (preg_match('/-en\./', $q) > 0) {
        $q = preg_replace('/-en\./', '-fr.', $q);
    }
    else if (preg_match('/-fr\./', $q) > 0) {
        $q = preg_replace('/-fr\./', '-en.', $q);
    } else {
        //if the Request URI doesn't end with a -en or a -fr then blank it and use the
        //$_SITE['gcwu_cmbland_href_' .$_PAGE['lang'.$i]] variable. The user should have
        //either set the variable to point to a static page change or it should be pointing
        //to the script file that's used for language changing.
        $q = '';
    }
    for($i=2; isset($_PAGE['lang'.$i]); $i++ ) {
        if( $q == '' ) {
            $q = $_SITE['gcwu_cmblang_href_' . $_PAGE['lang'.$i]];
        }
        echo '<li id="gcwu-gcnb-lang';
        if( $i-1 >= 2 ) {
            echo "-" .($i-1);
        }
        echo '">';
        echo '<a href="' .$q;
        echo '" lang="' .$_SITE['wb_meta_' . $_PAGE['lang'.$i]];
        echo '">' . $_SITE['gcwu_cmblang_text_' . $_PAGE['lang'.$i]];
        echo '</a></li>';
    }
}
```

I have updated the Pull Request to reflect these changes.

Best regards,

Michael

**Comment by michael-milette** [comment]
Hi @upsonp, noticed that this issue was still open. Just wanted to check in to find out if you had applied the fix yet.

**Comment by upsonp** [comment]
Thanks for keeping up on this @michael-milette, it's hard for me to keep up when I have so many other projects on the go. I made the minor update you suggested and just merged it into the Version 3.1 branch.

**Comment by michael-milette** [comment]
Thanks @upsonp !

Have a great day.

Best regards,

Michael

**Pull request closed without merging**
